/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: SEDENTARY,LIGHTLY_ACTIVE,MODERATELY_ACTIVE,VERY_ACTIVE
 */

@JsonClass(generateAdapter = false)
internal enum class ActivityLevel(val value: kotlin.String) {

    @Json(name = "sedentary")
    SEDENTARY("sedentary"),

    @Json(name = "lightly_active")
    LIGHTLY_ACTIVE("lightly_active"),

    @Json(name = "moderately_active")
    MODERATELY_ACTIVE("moderately_active"),

    @Json(name = "very_active")
    VERY_ACTIVE("very_active");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ActivityLevel) "$data" else null

        /**
         * Returns a valid [ActivityLevel] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ActivityLevel? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
