/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.AlternativeServing
import ai.january.partner.transport.models.NutritionFacts

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Catalog food id, or null when the producer matched none.
 * @param name Null only when the producer sent a food with no name.
 * @param brandName Null for generic (non-branded) foods.
 * @param nutrients
 * @param servings Servings to read the nutrition against. Empty when the recommender returned none — the key itself is always present.
 */


internal data class AlternativeFood (

    /* Catalog food id, or null when the producer matched none. */
    @Json(name = "id")
    val id: kotlin.String?,

    /* Null only when the producer sent a food with no name. */
    @Json(name = "name")
    val name: kotlin.String?,

    /* Null for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String?,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts,

    /* Servings to read the nutrition against. Empty when the recommender returned none — the key itself is always present. */
    @Json(name = "servings")
    val servings: kotlin.collections.List<AlternativeServing>

) {


}
