/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param effort `none` uses the standard analyzer; `xhigh` uses the reasoning-based analyzer.
 */


internal data class AnalysisReasoning (

    /* `none` uses the standard analyzer; `xhigh` uses the reasoning-based analyzer. */
    @Json(name = "effort")
    val effort: AnalysisReasoning.Effort

) {

    /**
     * `none` uses the standard analyzer; `xhigh` uses the reasoning-based analyzer.
     *
     * Values: NONE,XHIGH
     */
    @JsonClass(generateAdapter = false)
    internal enum class Effort(val value: kotlin.String) {
        @Json(name = "none") NONE("none"),
        @Json(name = "xhigh") XHIGH("xhigh");
    }

}
