/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param token The credential itself. Shown exactly once — it is stored only as a hash and can never be retrieved again.
 * @param expiresIn Seconds until the token expires, counted from the moment this response was produced. Compute expiry from this rather than from `expires_at` — a device clock that is wrong makes an absolute timestamp wrong with it.
 * @param expiresAt The same expiry as an absolute UTC instant, for logs and humans.
 * @param endUserId The end user this token is bound to, echoed back so a caller can assert it minted what it meant to.
 * @param scopes What this token may do — the exact scopes it was granted, echoed back so a caller can assert it minted what it meant to.
 */


internal data class ClientToken (

    /* The credential itself. Shown exactly once — it is stored only as a hash and can never be retrieved again. */
    @Json(name = "token")
    val token: kotlin.String,

    /* Seconds until the token expires, counted from the moment this response was produced. Compute expiry from this rather than from `expires_at` — a device clock that is wrong makes an absolute timestamp wrong with it. */
    @Json(name = "expires_in")
    val expiresIn: kotlin.Int,

    /* The same expiry as an absolute UTC instant, for logs and humans. */
    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    /* The end user this token is bound to, echoed back so a caller can assert it minted what it meant to. */
    @Json(name = "end_user_id")
    val endUserId: kotlin.String,

    /* What this token may do — the exact scopes it was granted, echoed back so a caller can assert it minted what it meant to. */
    @Json(name = "scopes")
    val scopes: kotlin.collections.List<ClientToken.Scopes>

) {

    /**
     * What this token may do — the exact scopes it was granted, echoed back so a caller can assert it minted what it meant to.
     *
     * Values: FOODS_COLON_READ,FOOD_ANALYSIS_COLON_WRITE,FOOD_LOGS_COLON_READ,FOOD_LOGS_COLON_WRITE,GLUCOSE_COLON_READ,RESTAURANTS_COLON_READ
     */
    @JsonClass(generateAdapter = false)
    internal enum class Scopes(val value: kotlin.String) {
        @Json(name = "foods:read") FOODS_COLON_READ("foods:read"),
        @Json(name = "food_analysis:write") FOOD_ANALYSIS_COLON_WRITE("food_analysis:write"),
        @Json(name = "food_logs:read") FOOD_LOGS_COLON_READ("food_logs:read"),
        @Json(name = "food_logs:write") FOOD_LOGS_COLON_WRITE("food_logs:write"),
        @Json(name = "glucose:read") GLUCOSE_COLON_READ("glucose:read"),
        @Json(name = "restaurants:read") RESTAURANTS_COLON_READ("restaurants:read");
    }

}
