/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutrientAmount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param calories
 * @param protein
 * @param carbohydrates
 * @param netCarbohydrates
 * @param totalFat
 * @param saturatedFat
 * @param fiber
 * @param totalSugars
 * @param addedSugars
 * @param sodium
 */


internal data class CompleteScanNutritionFacts (

    @Json(name = "calories")
    val calories: NutrientAmount? = null,

    @Json(name = "protein")
    val protein: NutrientAmount? = null,

    @Json(name = "carbohydrates")
    val carbohydrates: NutrientAmount? = null,

    @Json(name = "net_carbohydrates")
    val netCarbohydrates: NutrientAmount? = null,

    @Json(name = "total_fat")
    val totalFat: NutrientAmount? = null,

    @Json(name = "saturated_fat")
    val saturatedFat: NutrientAmount? = null,

    @Json(name = "fiber")
    val fiber: NutrientAmount? = null,

    @Json(name = "total_sugars")
    val totalSugars: NutrientAmount? = null,

    @Json(name = "added_sugars")
    val addedSugars: NutrientAmount? = null,

    @Json(name = "sodium")
    val sodium: NutrientAmount? = null

) {


}
