/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodLogInputServing

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param timestamp
 * @param id Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param serving
 */


internal data class ConsumedHistoricalFood (

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* Stable food identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "serving")
    val serving: FoodLogInputServing

) {


}
