/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param timestamp When the food was eaten. Must carry a timezone designator.
 * @param foodId Food id from a search or food-analysis result.
 * @param servingId One of the food's serving ids.
 * @param quantity How many of that serving were consumed.
 */


internal data class ConsumedHistoricalFood (

    /* When the food was eaten. Must carry a timezone designator. */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* Food id from a search or food-analysis result. */
    @Json(name = "food_id")
    val foodId: kotlin.String,

    /* One of the food's serving ids. */
    @Json(name = "serving_id")
    val servingId: kotlin.String,

    /* How many of that serving were consumed. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal

) {


}
