/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.CorrectionDetection
import ai.january.partner.transport.models.NutritionFacts

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param detections
 * @param mealName A name for the meal as a whole. Null on text analyses — the caller already has the words. Corrections preserve a null meal name.
 * @param totalNutrients
 */


internal data class CorrectionAnalysis (

    @Json(name = "detections")
    val detections: kotlin.collections.List<CorrectionDetection>,

    /* A name for the meal as a whole. Null on text analyses — the caller already has the words. Corrections preserve a null meal name. */
    @Json(name = "meal_name")
    val mealName: kotlin.String? = null,

    @Json(name = "total_nutrients")
    val totalNutrients: NutritionFacts? = null

) {


}
