/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodDetection

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param mealName The meal name from the meal-scan response.
 * @param detections The detections array from the meal-scan response, exactly as returned (all ten nutrient keys, non-empty servings).
 * @param userInput Plain-English description of what to correct.
 */


internal data class CorrectPhotoScanBody (

    /* The meal name from the meal-scan response. */
    @Json(name = "meal_name")
    val mealName: kotlin.String,

    /* The detections array from the meal-scan response, exactly as returned (all ten nutrient keys, non-empty servings). */
    @Json(name = "detections")
    val detections: kotlin.collections.List<FoodDetection>,

    /* Plain-English description of what to correct. */
    @Json(name = "user_input")
    val userInput: kotlin.String

) {


}
