/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.Weight

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param weight
 * @param createdAt When the weight was measured — any ISO-8601 offset; stored and returned in UTC with milliseconds. Omitted = now.
 */


internal data class CreateWeightLogBody (

    @Json(name = "weight")
    val weight: Weight,

    /* When the weight was measured — any ISO-8601 offset; stored and returned in UTC with milliseconds. Omitted = now. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}
