/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param endUserId Your stable ID for the end user this token acts as. The token is bound to it; requests made with the token act only on this user.
 * @param scopes What the token may do. **Required** — name only the scopes this token needs (least privilege), never the full set out of convenience. A read-only food-lookup screen asks for `[\"foods:read\"]`; a logging screen adds `food_logs:write`. Valid scopes: foods:read, food_analysis:write, food_logs:read, food_logs:write, glucose:read, restaurants:read.
 * @param ttlSeconds How long the token stays valid, in seconds. Between 300 and 7200; defaults to 1800.
 */


internal data class CreateClientTokenBody (

    /* Your stable ID for the end user this token acts as. The token is bound to it; requests made with the token act only on this user. */
    @Json(name = "end_user_id")
    val endUserId: kotlin.String,

    /* What the token may do. **Required** — name only the scopes this token needs (least privilege), never the full set out of convenience. A read-only food-lookup screen asks for `[\"foods:read\"]`; a logging screen adds `food_logs:write`. Valid scopes: foods:read, food_analysis:write, food_logs:read, food_logs:write, glucose:read, restaurants:read. */
    @Json(name = "scopes")
    val scopes: kotlin.collections.List<CreateClientTokenBody.Scopes>,

    /* How long the token stays valid, in seconds. Between 300 and 7200; defaults to 1800. */
    @Json(name = "ttl_seconds")
    val ttlSeconds: kotlin.Int? = 1800

) {

    /**
     * What the token may do. **Required** — name only the scopes this token needs (least privilege), never the full set out of convenience. A read-only food-lookup screen asks for `[\"foods:read\"]`; a logging screen adds `food_logs:write`. Valid scopes: foods:read, food_analysis:write, food_logs:read, food_logs:write, glucose:read, restaurants:read.
     *
     * Values: FOODS_COLON_READ,FOOD_ANALYSIS_COLON_WRITE,FOOD_LOGS_COLON_READ,FOOD_LOGS_COLON_WRITE,GLUCOSE_COLON_READ,RESTAURANTS_COLON_READ
     */
    @JsonClass(generateAdapter = false)
    internal enum class Scopes(val value: kotlin.String) {
        @Json(name = "foods:read") FOODS_COLON_READ("foods:read"),
        @Json(name = "food_analysis:write") FOOD_ANALYSIS_COLON_WRITE("food_analysis:write"),
        @Json(name = "food_logs:read") FOOD_LOGS_COLON_READ("food_logs:read"),
        @Json(name = "food_logs:write") FOOD_LOGS_COLON_WRITE("food_logs:write"),
        @Json(name = "glucose:read") GLUCOSE_COLON_READ("glucose:read"),
        @Json(name = "restaurants:read") RESTAURANTS_COLON_READ("restaurants:read");
    }

}
