/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param plan The plan this allowance comes from.
 * @param periodStart First day of the current billing period (UTC), inclusive.
 * @param periodEnd Last day of the current billing period (UTC), inclusive.
 * @param resetsAt When the allowance resets and `used_credits` returns to 0.
 * @param includedCredits Credits included in the plan for this period, or `null` when the plan has no ceiling.
 * @param usedCredits Credits used so far this period. Billable operations consume credits — how many depends on the operation and your plan — while failed calls cost nothing.
 * @param remainingCredits Credits left in this period, or `null` when the plan has no ceiling.
 */


internal data class CreditBalance (

    /* The plan this allowance comes from. */
    @Json(name = "plan")
    val plan: kotlin.String,

    /* First day of the current billing period (UTC), inclusive. */
    @Json(name = "period_start")
    val periodStart: java.time.LocalDate,

    /* Last day of the current billing period (UTC), inclusive. */
    @Json(name = "period_end")
    val periodEnd: java.time.LocalDate,

    /* When the allowance resets and `used_credits` returns to 0. */
    @Json(name = "resets_at")
    val resetsAt: java.time.OffsetDateTime,

    /* Credits included in the plan for this period, or `null` when the plan has no ceiling. */
    @Json(name = "included_credits")
    val includedCredits: kotlin.Int?,

    /* Credits used so far this period. Billable operations consume credits — how many depends on the operation and your plan — while failed calls cost nothing. */
    @Json(name = "used_credits")
    val usedCredits: kotlin.Int,

    /* Credits left in this period, or `null` when the plan has no ceiling. */
    @Json(name = "remaining_credits")
    val remainingCredits: kotlin.Int?

) {


}
