/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Null only when the producer sent a serving with no id.
 * @param quantity How much of `unit` this serving is; null when the producer reported none.
 * @param unit Null only when the producer sent a serving with no unit.
 * @param selectedQuantity Quantity parsed from the text ('2 cups' → 2); null on image analyses. Advisory — corrections reads the serving's own quantity.
 */


internal data class DetectedServing (

    /* Null only when the producer sent a serving with no id. */
    @Json(name = "id")
    val id: kotlin.String?,

    /* How much of `unit` this serving is; null when the producer reported none. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal?,

    /* Null only when the producer sent a serving with no unit. */
    @Json(name = "unit")
    val unit: kotlin.String?,

    /* Quantity parsed from the text ('2 cups' → 2); null on image analyses. Advisory — corrections reads the serving's own quantity. */
    @Json(name = "selected_quantity")
    val selectedQuantity: java.math.BigDecimal?

) {


}
