/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param name Null only when the producer sent a food with no name.
 * @param brandName Null for generic (non-branded) foods.
 * @param id Matched catalog food id. Pass it back as food_id when logging this food.
 * @param quantity Positive number of selected catalog servings consumed. Use it unchanged as food-log quantity. Display the consumed amount as food.quantity × food.serving.quantity, followed by food.serving.unit: 4 × 0.5 cup = 2 cups; 0.4 × 100 g = 40 g. Nutrients already describe this consumed portion; do not multiply them again.
 * @param serving
 * @param nutrients
 */


internal data class DetectedFood (

    /* Null only when the producer sent a food with no name. */
    @Json(name = "name")
    val name: kotlin.String?,

    /* Null for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String?,

    /* Matched catalog food id. Pass it back as food_id when logging this food. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Positive number of selected catalog servings consumed. Use it unchanged as food-log quantity. Display the consumed amount as food.quantity × food.serving.quantity, followed by food.serving.unit: 4 × 0.5 cup = 2 cups; 0.4 × 100 g = 40 g. Nutrients already describe this consumed portion; do not multiply them again. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    @Json(name = "serving")
    val serving: ServingSummary,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts

) {


}
