/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.CompleteScanNutritionFacts
import ai.january.partner.transport.models.DetectedServing

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param name
 * @param nutrients
 * @param servings Never empty: every detection producer guarantees at least one serving.
 * @param id Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param brandName Empty for generic (non-branded) foods.
 */


internal data class DetectedFood (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "nutrients")
    val nutrients: CompleteScanNutritionFacts,

    /* Never empty: every detection producer guarantees at least one serving. */
    @Json(name = "servings")
    val servings: kotlin.collections.List<DetectedServing>,

    /* Stable food identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    /* Empty for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String? = null

) {


}
