/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Catalog food id, or null when the producer matched none.
 * @param name Null only when the producer sent a food with no name.
 * @param brandName Null for generic (non-branded) foods.
 * @param quantity Number of catalog servings consumed, ready to use as food-log quantity. For 40 g from a 100 g serving this is 0.4. Null when the producer supplied no usable portion.
 * @param serving
 * @param nutrients
 */


internal data class DetectedFood (

    /* Catalog food id, or null when the producer matched none. */
    @Json(name = "id")
    val id: kotlin.String?,

    /* Null only when the producer sent a food with no name. */
    @Json(name = "name")
    val name: kotlin.String?,

    /* Null for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String?,

    /* Number of catalog servings consumed, ready to use as food-log quantity. For 40 g from a 100 g serving this is 0.4. Null when the producer supplied no usable portion. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal?,

    @Json(name = "serving")
    val serving: ServingSummary,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts

) {


}
