/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: NONE,VEGETARIAN,VEGAN,KETO,PALEO,PESCATARIAN,LOW_CARBOHYDRATE,HIGH_PROTEIN,KOSHER,HALAL
 */

@JsonClass(generateAdapter = false)
internal enum class DietPreference(val value: kotlin.String) {

    @Json(name = "None")
    NONE("None"),

    @Json(name = "Vegetarian")
    VEGETARIAN("Vegetarian"),

    @Json(name = "Vegan")
    VEGAN("Vegan"),

    @Json(name = "Keto")
    KETO("Keto"),

    @Json(name = "Paleo")
    PALEO("Paleo"),

    @Json(name = "Pescatarian")
    PESCATARIAN("Pescatarian"),

    @Json(name = "Low carbohydrate")
    LOW_CARBOHYDRATE("Low carbohydrate"),

    @Json(name = "High protein")
    HIGH_PROTEIN("High protein"),

    @Json(name = "Kosher")
    KOSHER("Kosher"),

    @Json(name = "Halal")
    HALAL("Halal");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DietPreference) "$data" else null

        /**
         * Returns a valid [DietPreference] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DietPreference? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
