/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: NONE,GLUTEN,LACTOSE,YEAST,TREE_NUTS,PEANUTS,DAIRY,EGGS,SULFITES,SOY,WHEAT,SHELLFISH,FISH,MUSHROOMS,SESAME,MONOSODIUM_GLUTAMATE_LEFT_PARENTHESIS_MSG_RIGHT_PARENTHESIS,CAFFEINE,FODMAPS
 */

@JsonClass(generateAdapter = false)
internal enum class DietRestriction(val value: kotlin.String) {

    @Json(name = "None")
    NONE("None"),

    @Json(name = "Gluten")
    GLUTEN("Gluten"),

    @Json(name = "Lactose")
    LACTOSE("Lactose"),

    @Json(name = "Yeast")
    YEAST("Yeast"),

    @Json(name = "Tree nuts")
    TREE_NUTS("Tree nuts"),

    @Json(name = "Peanuts")
    PEANUTS("Peanuts"),

    @Json(name = "Dairy")
    DAIRY("Dairy"),

    @Json(name = "Eggs")
    EGGS("Eggs"),

    @Json(name = "Sulfites")
    SULFITES("Sulfites"),

    @Json(name = "Soy")
    SOY("Soy"),

    @Json(name = "Wheat")
    WHEAT("Wheat"),

    @Json(name = "Shellfish")
    SHELLFISH("Shellfish"),

    @Json(name = "Fish")
    FISH("Fish"),

    @Json(name = "Mushrooms")
    MUSHROOMS("Mushrooms"),

    @Json(name = "Sesame")
    SESAME("Sesame"),

    @Json(name = "Monosodium glutamate (MSG)")
    MONOSODIUM_GLUTAMATE_LEFT_PARENTHESIS_MSG_RIGHT_PARENTHESIS("Monosodium glutamate (MSG)"),

    @Json(name = "Caffeine")
    CAFFEINE("Caffeine"),

    @Json(name = "FODMAPs")
    FODMAPS("FODMAPs");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DietRestriction) "$data" else null

        /**
         * Returns a valid [DietRestriction] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DietRestriction? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
