/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param message A developer-facing explanation of what went wrong and how to fix it.
 * @param code A stable machine-readable identifier for the class of failure — build retry logic on this, never on message wording. Current values: invalid_request, unauthorized, forbidden, not_found, payload_too_large, rate_limited, internal_error, upstream_error, service_unavailable, upstream_timeout. Only rate_limited and the four 5xx codes are safe to retry (with backoff). New codes may be added over time; treat an unknown code according to its HTTP status class.
 * @param docsUrl Link to the developer documentation for this API version.
 */


internal data class ErrorResponse (

    /* A developer-facing explanation of what went wrong and how to fix it. */
    @Json(name = "message")
    val message: kotlin.String,

    /* A stable machine-readable identifier for the class of failure — build retry logic on this, never on message wording. Current values: invalid_request, unauthorized, forbidden, not_found, payload_too_large, rate_limited, internal_error, upstream_error, service_unavailable, upstream_timeout. Only rate_limited and the four 5xx codes are safe to retry (with backoff). New codes may be added over time; treat an unknown code according to its HTTP status class. */
    @Json(name = "code")
    val code: kotlin.String,

    /* Link to the developer documentation for this API version. */
    @Json(name = "docs_url")
    val docsUrl: kotlin.String

) {


}
