/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.LoggedFood

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Stable food-log identifier; the upstream 400 response explicitly rejects non-UUID values.
 * @param foods
 * @param timestampUtc
 * @param name
 */


internal data class FoodLog (

    /* Stable food-log identifier; the upstream 400 response explicitly rejects non-UUID values. */
    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "foods")
    val foods: kotlin.collections.List<LoggedFood>,

    @Json(name = "timestamp_utc")
    val timestampUtc: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String? = null

) {


}
