/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.ServingOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param name
 * @param brandName
 * @param energy
 * @param protein
 * @param carbs
 * @param netCarbs
 * @param fat
 * @param fatTotalSaturated
 * @param fiber
 * @param sugars
 * @param addedSugars
 * @param sodium
 * @param potassium
 * @param cholesterol
 * @param gi Glycemic index.
 * @param gl Glycemic load.
 * @param photoUrl
 * @param servings
 */


internal data class FoodSearchItem (

    /* Stable food identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "brand_name")
    val brandName: kotlin.String?,

    @Json(name = "energy")
    val energy: java.math.BigDecimal?,

    @Json(name = "protein")
    val protein: java.math.BigDecimal?,

    @Json(name = "carbs")
    val carbs: java.math.BigDecimal?,

    @Json(name = "net_carbs")
    val netCarbs: java.math.BigDecimal?,

    @Json(name = "fat")
    val fat: java.math.BigDecimal?,

    @Json(name = "fat_total_saturated")
    val fatTotalSaturated: java.math.BigDecimal?,

    @Json(name = "fiber")
    val fiber: java.math.BigDecimal?,

    @Json(name = "sugars")
    val sugars: java.math.BigDecimal?,

    @Json(name = "added_sugars")
    val addedSugars: java.math.BigDecimal?,

    @Json(name = "sodium")
    val sodium: java.math.BigDecimal?,

    @Json(name = "potassium")
    val potassium: java.math.BigDecimal?,

    @Json(name = "cholesterol")
    val cholesterol: java.math.BigDecimal?,

    /* Glycemic index. */
    @Json(name = "gi")
    val gi: java.math.BigDecimal?,

    /* Glycemic load. */
    @Json(name = "gl")
    val gl: java.math.BigDecimal?,

    @Json(name = "photo_url")
    val photoUrl: kotlin.String?,

    @Json(name = "servings")
    val servings: kotlin.collections.List<ServingOption>

) {


}
