/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodSearchItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param totalCount Total number of matches in the database; may exceed the number of items returned.
 * @param items
 */


internal data class FoodSearchResults (

    /* Total number of matches in the database; may exceed the number of items returned. */
    @Json(name = "total_count")
    val totalCount: java.math.BigDecimal,

    @Json(name = "items")
    val items: kotlin.collections.List<FoodSearchItem>

) {


}
