/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param logsCount Logs in the whole range.
 * @param daysWithLogs Distinct local calendar dates in the range that carry at least one log.
 * @param nutrients
 */


internal data class FoodLogSummaryTotals (

    /* Logs in the whole range. */
    @Json(name = "logs_count")
    val logsCount: kotlin.Int,

    /* Distinct local calendar dates in the range that carry at least one log. */
    @Json(name = "days_with_logs")
    val daysWithLogs: kotlin.Int,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts

) {


}
