/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param startDate First local calendar date this bucket covers. Clipped to the requested range, so the first week bucket may be partial.
 * @param endDate Last local calendar date this bucket covers, inclusive. Equal to start_date when grouping by day.
 * @param logsCount How many logs fall in this bucket.
 * @param daysWithLogs How many distinct local calendar dates in this bucket carry at least one log.
 * @param nutrients
 */


internal data class FoodLogSummaryBucket (

    /* First local calendar date this bucket covers. Clipped to the requested range, so the first week bucket may be partial. */
    @Json(name = "start_date")
    val startDate: java.time.LocalDate,

    /* Last local calendar date this bucket covers, inclusive. Equal to start_date when grouping by day. */
    @Json(name = "end_date")
    val endDate: java.time.LocalDate,

    /* How many logs fall in this bucket. */
    @Json(name = "logs_count")
    val logsCount: kotlin.Int,

    /* How many distinct local calendar dates in this bucket carry at least one log. */
    @Json(name = "days_with_logs")
    val daysWithLogs: kotlin.Int,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts

) {


}
