/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param name Generic foods are lowercase; branded foods keep their product name.
 * @param brandName Absent for generic (non-branded) foods.
 * @param imageUrl Thumbnail of the food, when the database has one.
 * @param nutrients
 */


internal data class FoodSuggestion (

    /* Stable food identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long,

    /* Generic foods are lowercase; branded foods keep their product name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Absent for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String? = null,

    /* Thumbnail of the food, when the database has one. */
    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts? = null

) {


}
