/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.CompleteScanNutritionFacts
import ai.january.partner.transport.models.FoodDetection

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param detections Detected foods. Always present — an empty array means nothing was recognized.
 * @param mealName
 * @param totalNutrients
 */


internal data class FoodScan (

    /* Detected foods. Always present — an empty array means nothing was recognized. */
    @Json(name = "detections")
    val detections: kotlin.collections.List<FoodDetection>,

    @Json(name = "meal_name")
    val mealName: kotlin.String? = null,

    @Json(name = "total_nutrients")
    val totalNutrients: CompleteScanNutritionFacts? = null

) {


}
