/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param name
 * @param nutrients
 * @param servings
 * @param brandName Absent for generic (non-branded) foods.
 * @param glycemicIndex Glycemic index.
 * @param glycemicLoad Glycemic load.
 * @param imageUrl URL of a picture of the food, when the database has one.
 */


internal data class FoodSearchItem (

    /* Stable food identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts,

    @Json(name = "servings")
    val servings: kotlin.collections.List<ServingOption>,

    /* Absent for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String? = null,

    /* Glycemic index. */
    @Json(name = "glycemic_index")
    val glycemicIndex: java.math.BigDecimal? = null,

    /* Glycemic load. */
    @Json(name = "glycemic_load")
    val glycemicLoad: java.math.BigDecimal? = null,

    /* URL of a picture of the food, when the database has one. */
    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null

) {


}
