/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param foodId Opaque food identifier; pass it back verbatim.
 * @param servingId Opaque serving identifier; pass it back verbatim.
 * @param quantity How many of that serving were consumed.
 */


internal data class FoodLogInputFood (

    /* Opaque food identifier; pass it back verbatim. */
    @Json(name = "food_id")
    val foodId: kotlin.String,

    /* Opaque serving identifier; pass it back verbatim. */
    @Json(name = "serving_id")
    val servingId: kotlin.String,

    /* How many of that serving were consumed. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal

) {


}
