/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodLogSummaryAverage
import ai.january.partner.transport.models.FoodLogSummaryBucket
import ai.january.partner.transport.models.FoodLogSummaryTotals

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param groupBy The bucket size used, echoing the request.
 * @param weekStart The weekday week buckets begin on. Always present; `null` when `group_by=day`, where it does not apply.
 * @param timezone The IANA timezone the buckets were cut in — the canonical spelling of what was requested.
 * @param startDate First local calendar date of the summarized range, echoing the request.
 * @param endDate Last local calendar date of the summarized range, inclusive.
 * @param buckets The buckets tiling the range, in chronological order and covering it end to end — a day or week with no logs is returned with zero counts rather than skipped.
 * @param totals
 * @param averagePerLoggedDay
 */


internal data class FoodLogSummary (

    /* The bucket size used, echoing the request. */
    @Json(name = "group_by")
    val groupBy: FoodLogSummary.GroupBy,

    /* The weekday week buckets begin on. Always present; `null` when `group_by=day`, where it does not apply. */
    @Json(name = "week_start")
    val weekStart: FoodLogSummary.WeekStart?,

    /* The IANA timezone the buckets were cut in — the canonical spelling of what was requested. */
    @Json(name = "timezone")
    val timezone: kotlin.String,

    /* First local calendar date of the summarized range, echoing the request. */
    @Json(name = "start_date")
    val startDate: java.time.LocalDate,

    /* Last local calendar date of the summarized range, inclusive. */
    @Json(name = "end_date")
    val endDate: java.time.LocalDate,

    /* The buckets tiling the range, in chronological order and covering it end to end — a day or week with no logs is returned with zero counts rather than skipped. */
    @Json(name = "buckets")
    val buckets: kotlin.collections.List<FoodLogSummaryBucket>,

    @Json(name = "totals")
    val totals: FoodLogSummaryTotals,

    @Json(name = "average_per_logged_day")
    val averagePerLoggedDay: FoodLogSummaryAverage

) {

    /**
     * The bucket size used, echoing the request.
     *
     * Values: DAY,WEEK
     */
    @JsonClass(generateAdapter = false)
    internal enum class GroupBy(val value: kotlin.String) {
        @Json(name = "day") DAY("day"),
        @Json(name = "week") WEEK("week");
    }
    /**
     * The weekday week buckets begin on. Always present; `null` when `group_by=day`, where it does not apply.
     *
     * Values: MONDAY,SUNDAY
     */
    @JsonClass(generateAdapter = false)
    internal enum class WeekStart(val value: kotlin.String) {
        @Json(name = "monday") MONDAY("monday"),
        @Json(name = "sunday") SUNDAY("sunday");
    }

}
