/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.DetectedFood

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param confidence How sure the vision model is of this detection. Null on text analyses and on corrected results.
 * @param food
 */


internal data class FoodDetection (

    /* How sure the vision model is of this detection. Null on text analyses and on corrected results. */
    @Json(name = "confidence")
    val confidence: kotlin.String?,

    @Json(name = "food")
    val food: DetectedFood

) {


}
