/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.LoggedFood

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Save this id to update or delete the log. Null only when the upstream sent a log with no id — such a log cannot be addressed.
 * @param foods
 * @param eatenAt When the meal was eaten. UTC, with milliseconds.
 * @param name Null when no name was given.
 */


internal data class FoodLog (

    /* Save this id to update or delete the log. Null only when the upstream sent a log with no id — such a log cannot be addressed. */
    @Json(name = "id")
    val id: kotlin.String?,

    @Json(name = "foods")
    val foods: kotlin.collections.List<LoggedFood>,

    /* When the meal was eaten. UTC, with milliseconds. */
    @Json(name = "eaten_at")
    val eatenAt: java.time.OffsetDateTime,

    /* Null when no name was given. */
    @Json(name = "name")
    val name: kotlin.String?

) {


}
