/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Stable serving identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param quantity How many of that serving were consumed.
 */


internal data class FoodLogInputServing (

    /* Stable serving identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long,

    /* How many of that serving were consumed. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal

) {


}
