/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.GlucoseChart
import ai.january.partner.transport.models.GlucosePredictionPoint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param prediction The predicted glucose curve at 15-minute intervals, starting at start_time.
 * @param impactScore The meal's overall glucose impact.
 * @param chart
 */


internal data class GlucosePrediction (

    /* The predicted glucose curve at 15-minute intervals, starting at start_time. */
    @Json(name = "prediction")
    val prediction: kotlin.collections.List<GlucosePredictionPoint>,

    /* The meal's overall glucose impact. */
    @Json(name = "impact_score")
    val impactScore: kotlin.String,

    @Json(name = "chart")
    val chart: GlucoseChart

) {


}
