/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.ActivityLevel
import ai.january.partner.transport.models.Gender
import ai.january.partner.transport.models.MedicalCondition

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param age
 * @param gender
 * @param height Inches.
 * @param weight Pounds.
 * @param activityLevel
 * @param healthConditions Case-sensitive. Type 1 diabetes is not supported by the prediction model.
 */


internal data class GlucosePredictionProfile (

    @Json(name = "age")
    val age: java.math.BigDecimal,

    @Json(name = "gender")
    val gender: Gender,

    /* Inches. */
    @Json(name = "height")
    val height: java.math.BigDecimal,

    /* Pounds. */
    @Json(name = "weight")
    val weight: java.math.BigDecimal,

    @Json(name = "activity_level")
    val activityLevel: ActivityLevel? = null,

    /* Case-sensitive. Type 1 diabetes is not supported by the prediction model. */
    @Json(name = "health_conditions")
    val healthConditions: kotlin.collections.List<MedicalCondition>? = null

) {


}
