/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.ActivityLevel
import ai.january.partner.transport.models.Height
import ai.january.partner.transport.models.MedicalCondition
import ai.january.partner.transport.models.Sex
import ai.january.partner.transport.models.Weight

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param age
 * @param sex
 * @param height
 * @param weight
 * @param activityLevel
 * @param healthConditions Omit it (or send []) if none apply. Type 1 diabetes is not supported by the prediction model.
 */


internal data class GlucosePredictionProfile (

    @Json(name = "age")
    val age: java.math.BigDecimal,

    @Json(name = "sex")
    val sex: Sex,

    @Json(name = "height")
    val height: Height,

    @Json(name = "weight")
    val weight: Weight,

    @Json(name = "activity_level")
    val activityLevel: ActivityLevel? = null,

    /* Omit it (or send []) if none apply. Type 1 diabetes is not supported by the prediction model. */
    @Json(name = "health_conditions")
    val healthConditions: kotlin.collections.List<MedicalCondition>? = null

) {


}
