/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param minutes Minutes after start_time.
 * @param `value` Predicted glucose, mg/dL.
 */


internal data class GlucosePredictionPoint (

    /* Minutes after start_time. */
    @Json(name = "minutes")
    val minutes: java.math.BigDecimal,

    /* Predicted glucose, mg/dL. */
    @Json(name = "value")
    val `value`: java.math.BigDecimal

) {


}
