/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param cgp The predicted glucose curve as [minutes after start_time, mg/dL] points at 15-minute intervals.
 * @param scoring
 * @param cgpMin The chart's suggested Y-axis lower bound (mg/dL) — a fixed target-range bound, NOT the minimum of the predicted curve.
 * @param cgpMax The chart's suggested Y-axis upper bound (mg/dL): 180 with Type 2 diabetes in health_conditions, otherwise 140. NOT the maximum of the predicted curve.
 */


internal data class GlucosePrediction (

    /* The predicted glucose curve as [minutes after start_time, mg/dL] points at 15-minute intervals. */
    @Json(name = "cgp")
    val cgp: kotlin.collections.List<kotlin.collections.List<java.math.BigDecimal>>,

    @Json(name = "scoring")
    val scoring: kotlin.String,

    /* The chart's suggested Y-axis lower bound (mg/dL) — a fixed target-range bound, NOT the minimum of the predicted curve. */
    @Json(name = "cgp_min")
    val cgpMin: java.math.BigDecimal,

    /* The chart's suggested Y-axis upper bound (mg/dL): 180 with Type 2 diabetes in health_conditions, otherwise 140. NOT the maximum of the predicted curve. */
    @Json(name = "cgp_max")
    val cgpMax: java.math.BigDecimal

) {


}
