/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.HeightUnit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param `value` Accepted range depends on unit: 20–108 in, 50–275 cm.
 * @param unit
 */


internal data class Height (

    /* Accepted range depends on unit: 20–108 in, 50–275 cm. */
    @Json(name = "value")
    val `value`: java.math.BigDecimal,

    @Json(name = "unit")
    val unit: HeightUnit

) {


}
