/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.DailyWeight

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param items One entry per day that has a weight, oldest first. Days with no weight are absent. An empty list is a valid result.
 */


internal data class ListWeightLogsResponse (

    /* One entry per day that has a weight, oldest first. Days with no weight are absent. An empty list is a valid result. */
    @Json(name = "items")
    val items: kotlin.collections.List<DailyWeight>

) {


}
