/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodLog

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param totalCount
 * @param items Logs in the range, ordered by timestamp. An empty list is a valid result.
 */


internal data class ListFoodLogsResponse (

    @Json(name = "total_count")
    val totalCount: java.math.BigDecimal,

    /* Logs in the range, ordered by timestamp. An empty list is a valid result. */
    @Json(name = "items")
    val items: kotlin.collections.List<FoodLog>

) {


}
