/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.ConsumedServing
import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingDetails

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
 * @param name
 * @param nutrients
 * @param consumedServing
 * @param servingDetails
 * @param brandName
 * @param imageUrl
 * @param glycemicIndex
 * @param glycemicLoad
 */


internal data class LoggedFood (

    /* Stable food identifier, provisionally narrowed to JavaScript's safe integer range. */
    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts,

    @Json(name = "consumed_serving")
    val consumedServing: ConsumedServing,

    @Json(name = "serving_details")
    val servingDetails: ServingDetails,

    @Json(name = "brand_name")
    val brandName: kotlin.String? = null,

    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "glycemic_index")
    val glycemicIndex: java.math.BigDecimal? = null,

    @Json(name = "glycemic_load")
    val glycemicLoad: java.math.BigDecimal? = null

) {


}
