/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingDetails

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param foodId Food id from a search or food-analysis result. Null only when the upstream sent a food with no id.
 * @param name Null only when the upstream sent none.
 * @param brandName Null for generic (non-branded) foods.
 * @param imageUrl
 * @param glycemicIndex
 * @param glycemicLoad
 * @param nutrients
 * @param quantity How many of the serving below were consumed. Null only when the upstream sent no consumed quantity.
 * @param serving
 */


internal data class LoggedFood (

    /* Food id from a search or food-analysis result. Null only when the upstream sent a food with no id. */
    @Json(name = "food_id")
    val foodId: kotlin.String?,

    /* Null only when the upstream sent none. */
    @Json(name = "name")
    val name: kotlin.String?,

    /* Null for generic (non-branded) foods. */
    @Json(name = "brand_name")
    val brandName: kotlin.String?,

    @Json(name = "image_url")
    val imageUrl: kotlin.String?,

    @Json(name = "glycemic_index")
    val glycemicIndex: java.math.BigDecimal?,

    @Json(name = "glycemic_load")
    val glycemicLoad: java.math.BigDecimal?,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts,

    /* How many of the serving below were consumed. Null only when the upstream sent no consumed quantity. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal?,

    @Json(name = "serving")
    val serving: ServingDetails

) {


}
