/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.CgmReading
import ai.january.partner.transport.models.ConsumedHistoricalFood
import ai.january.partner.transport.models.FoodLogInputFood
import ai.january.partner.transport.models.GlucosePredictionProfile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param userProfile
 * @param foods The meal to predict the glucose response for.
 * @param startTime When the meal is (or will be) eaten. Must carry a timezone designator.
 * @param cgmData Optional CGM history for personalization; requires consumed_foods.
 * @param consumedFoods The meals eaten during the CGM history; requires cgm_data.
 */


internal data class PredictGlucoseBody (

    @Json(name = "user_profile")
    val userProfile: GlucosePredictionProfile,

    /* The meal to predict the glucose response for. */
    @Json(name = "foods")
    val foods: kotlin.collections.List<FoodLogInputFood>,

    /* When the meal is (or will be) eaten. Must carry a timezone designator. */
    @Json(name = "start_time")
    val startTime: java.time.OffsetDateTime,

    /* Optional CGM history for personalization; requires consumed_foods. */
    @Json(name = "cgm_data")
    val cgmData: kotlin.collections.List<CgmReading>? = null,

    /* The meals eaten during the CGM history; requires cgm_data. */
    @Json(name = "consumed_foods")
    val consumedFoods: kotlin.collections.List<ConsumedHistoricalFood>? = null

) {


}
