/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param type Always `restaurant`: this endpoint answers places only. For dishes, use `GET /v1.2/menu-items`.
 * @param id
 * @param name Null only when the source has no name for the place.
 * @param isChain Whether this location belongs to a chain; null when unknown.
 * @param distanceMeters Distance from (latitude, longitude) in meters; null when the source cannot place this result.
 * @param city
 * @param address1
 * @param address2 Second address line; null when there is none.
 */


internal data class Restaurant (

    /* Always `restaurant`: this endpoint answers places only. For dishes, use `GET /v1.2/menu-items`. */
    @Json(name = "type")
    val type: Restaurant.Type,

    @Json(name = "id")
    val id: kotlin.String,

    /* Null only when the source has no name for the place. */
    @Json(name = "name")
    val name: kotlin.String?,

    /* Whether this location belongs to a chain; null when unknown. */
    @Json(name = "is_chain")
    val isChain: kotlin.Boolean?,

    /* Distance from (latitude, longitude) in meters; null when the source cannot place this result. */
    @Json(name = "distance_meters")
    val distanceMeters: java.math.BigDecimal?,

    @Json(name = "city")
    val city: kotlin.String?,

    @Json(name = "address1")
    val address1: kotlin.String?,

    /* Second address line; null when there is none. */
    @Json(name = "address2")
    val address2: kotlin.String?

) {

    /**
     * Always `restaurant`: this endpoint answers places only. For dishes, use `GET /v1.2/menu-items`.
     *
     * Values: RESTAURANT
     */
    @JsonClass(generateAdapter = false)
    internal enum class Type(val value: kotlin.String) {
        @Json(name = "restaurant") RESTAURANT("restaurant");
    }

}
