/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.ServingOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param type
 * @param id Opaque restaurant menu-item identifier.
 * @param name
 * @param restaurantName
 * @param servings
 * @param isChain
 * @param energy Calories (kcal).
 * @param protein
 * @param carbs
 * @param netCarbs
 * @param fat
 * @param fiber
 * @param sugars
 * @param addedSugars
 * @param gi Glycemic index.
 * @param gl Glycemic load.
 * @param photoUrl
 * @param distance Distance from (latitude, longitude) in meters.
 */


internal data class RestaurantMenuItem (

    @Json(name = "type")
    val type: kotlin.String,

    /* Opaque restaurant menu-item identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "restaurant_name")
    val restaurantName: kotlin.String,

    @Json(name = "servings")
    val servings: kotlin.collections.List<ServingOption>,

    @Json(name = "is_chain")
    val isChain: kotlin.Boolean? = null,

    /* Calories (kcal). */
    @Json(name = "energy")
    val energy: java.math.BigDecimal? = null,

    @Json(name = "protein")
    val protein: java.math.BigDecimal? = null,

    @Json(name = "carbs")
    val carbs: java.math.BigDecimal? = null,

    @Json(name = "net_carbs")
    val netCarbs: java.math.BigDecimal? = null,

    @Json(name = "fat")
    val fat: java.math.BigDecimal? = null,

    @Json(name = "fiber")
    val fiber: java.math.BigDecimal? = null,

    @Json(name = "sugars")
    val sugars: java.math.BigDecimal? = null,

    @Json(name = "added_sugars")
    val addedSugars: java.math.BigDecimal? = null,

    /* Glycemic index. */
    @Json(name = "gi")
    val gi: java.math.BigDecimal? = null,

    /* Glycemic load. */
    @Json(name = "gl")
    val gl: java.math.BigDecimal? = null,

    @Json(name = "photo_url")
    val photoUrl: kotlin.String? = null,

    /* Distance from (latitude, longitude) in meters. */
    @Json(name = "distance")
    val distance: java.math.BigDecimal? = null

) {


}
