/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param type Always `menu_item`: this endpoint answers dishes only. For the places themselves, use `GET /v1.2/restaurants`.
 * @param id Opaque restaurant menu-item identifier.
 * @param name Null only when the menu source has no name for the dish.
 * @param restaurantName Null when the menu source names no restaurant.
 * @param isChain Whether the restaurant belongs to a chain; null when unknown.
 * @param nutrients
 * @param glycemicIndex Glycemic index; null when the source has none.
 * @param glycemicLoad Glycemic load; null when the source has none.
 * @param imageUrl URL of a picture of the dish; null when the source has none.
 * @param distanceMeters Distance from (latitude, longitude) in meters.
 * @param servings
 */


internal data class RestaurantMenuSearchItem (

    /* Always `menu_item`: this endpoint answers dishes only. For the places themselves, use `GET /v1.2/restaurants`. */
    @Json(name = "type")
    val type: RestaurantMenuSearchItem.Type,

    /* Opaque restaurant menu-item identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Null only when the menu source has no name for the dish. */
    @Json(name = "name")
    val name: kotlin.String?,

    /* Null when the menu source names no restaurant. */
    @Json(name = "restaurant_name")
    val restaurantName: kotlin.String?,

    /* Whether the restaurant belongs to a chain; null when unknown. */
    @Json(name = "is_chain")
    val isChain: kotlin.Boolean?,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts,

    /* Glycemic index; null when the source has none. */
    @Json(name = "glycemic_index")
    val glycemicIndex: java.math.BigDecimal?,

    /* Glycemic load; null when the source has none. */
    @Json(name = "glycemic_load")
    val glycemicLoad: java.math.BigDecimal?,

    /* URL of a picture of the dish; null when the source has none. */
    @Json(name = "image_url")
    val imageUrl: kotlin.String?,

    /* Distance from (latitude, longitude) in meters. */
    @Json(name = "distance_meters")
    val distanceMeters: java.math.BigDecimal?,

    @Json(name = "servings")
    val servings: kotlin.collections.List<ServingOption>

) {

    /**
     * Always `menu_item`: this endpoint answers dishes only. For the places themselves, use `GET /v1.2/restaurants`.
     *
     * Values: MENU_ITEM
     */
    @JsonClass(generateAdapter = false)
    internal enum class Type(val value: kotlin.String) {
        @Json(name = "menu_item") MENU_ITEM("menu_item");
    }

}
