/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Food id of the dish — the same id `GET /v1.2/foods/{food_id}` and `POST /v1.2/food-logs` take. Null only when the menu source carries no id for the row.
 * @param name Null only when the menu source has no name for the dish.
 * @param nutrients
 * @param glycemicIndex Glycemic index; null when the source has none.
 * @param glycemicLoad Glycemic load; null when the source has none.
 * @param servings The serving the nutrition is given for. `GET /v1.2/foods/{food_id}` returns the complete list of servings.
 */


internal data class RestaurantMenuItem (

    /* Food id of the dish — the same id `GET /v1.2/foods/{food_id}` and `POST /v1.2/food-logs` take. Null only when the menu source carries no id for the row. */
    @Json(name = "id")
    val id: kotlin.String?,

    /* Null only when the menu source has no name for the dish. */
    @Json(name = "name")
    val name: kotlin.String?,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts,

    /* Glycemic index; null when the source has none. */
    @Json(name = "glycemic_index")
    val glycemicIndex: java.math.BigDecimal?,

    /* Glycemic load; null when the source has none. */
    @Json(name = "glycemic_load")
    val glycemicLoad: java.math.BigDecimal?,

    /* The serving the nutrition is given for. `GET /v1.2/foods/{food_id}` returns the complete list of servings. */
    @Json(name = "servings")
    val servings: kotlin.collections.List<ServingOption>

) {


}
