/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param type When coordinates are provided and the name matches no restaurant, results may be menu items instead.
 * @param id
 * @param name
 * @param isChain
 * @param distance Distance from (latitude, longitude) in meters; present only when coordinates were provided.
 * @param city
 * @param address1
 * @param address2
 */


internal data class Restaurant (

    /* When coordinates are provided and the name matches no restaurant, results may be menu items instead. */
    @Json(name = "type")
    val type: Restaurant.Type,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "is_chain")
    val isChain: kotlin.Boolean? = null,

    /* Distance from (latitude, longitude) in meters; present only when coordinates were provided. */
    @Json(name = "distance")
    val distance: java.math.BigDecimal? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "address1")
    val address1: kotlin.String? = null,

    @Json(name = "address2")
    val address2: kotlin.String? = null

) {

    /**
     * When coordinates are provided and the name matches no restaurant, results may be menu items instead.
     *
     * Values: RESTAURANT,MENU_ITEM
     */
    @JsonClass(generateAdapter = false)
    internal enum class Type(val value: kotlin.String) {
        @Json(name = "restaurant") RESTAURANT("restaurant"),
        @Json(name = "menu_item") MENU_ITEM("menu_item");
    }

}
