/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.NutritionFacts
import ai.january.partner.transport.models.ServingOption

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param type
 * @param id Opaque restaurant menu-item identifier.
 * @param name
 * @param restaurantName
 * @param servings
 * @param isChain
 * @param nutrients
 * @param glycemicIndex Glycemic index.
 * @param glycemicLoad Glycemic load.
 * @param imageUrl URL of a picture of the dish, when the source has one.
 * @param distance Distance from (latitude, longitude) in meters.
 */


internal data class RestaurantMenuItem (

    @Json(name = "type")
    val type: kotlin.String,

    /* Opaque restaurant menu-item identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "restaurant_name")
    val restaurantName: kotlin.String,

    @Json(name = "servings")
    val servings: kotlin.collections.List<ServingOption>,

    @Json(name = "is_chain")
    val isChain: kotlin.Boolean? = null,

    @Json(name = "nutrients")
    val nutrients: NutritionFacts? = null,

    /* Glycemic index. */
    @Json(name = "glycemic_index")
    val glycemicIndex: java.math.BigDecimal? = null,

    /* Glycemic load. */
    @Json(name = "glycemic_load")
    val glycemicLoad: java.math.BigDecimal? = null,

    /* URL of a picture of the dish, when the source has one. */
    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    /* Distance from (latitude, longitude) in meters. */
    @Json(name = "distance")
    val distance: java.math.BigDecimal? = null

) {


}
