/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.CompleteScanNutritionFacts
import ai.january.partner.transport.models.NaturalLanguageFoodDetection

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param detections
 * @param totalNutrients
 */


internal data class SearchFoodsByNaturalLanguageResponse (

    @Json(name = "detections")
    val detections: kotlin.collections.List<NaturalLanguageFoodDetection>,

    @Json(name = "total_nutrients")
    val totalNutrients: CompleteScanNutritionFacts? = null

) {


}
