/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Null only when the upstream sent a serving with no id.
 * @param quantity How many units make up one of this serving, e.g. 1 for \"1 cup\". Null when the upstream reported none.
 * @param unit Null only when the upstream sent a serving with no unit.
 * @param weightGrams Null when the upstream has no gram weight for this serving.
 */


internal data class ServingDetails (

    /* Null only when the upstream sent a serving with no id. */
    @Json(name = "id")
    val id: kotlin.String?,

    /* How many units make up one of this serving, e.g. 1 for \"1 cup\". Null when the upstream reported none. */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal?,

    /* Null only when the upstream sent a serving with no unit. */
    @Json(name = "unit")
    val unit: kotlin.String?,

    /* Null when the upstream has no gram weight for this serving. */
    @Json(name = "weight_grams")
    val weightGrams: java.math.BigDecimal?

) {


}
