/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Opaque serving id; may look numeric but is always a string.
 * @param quantity
 * @param unit
 * @param scalingFactor Multiplier applied to the food's nutrition values for this serving.
 * @param weightGrams
 * @param isPrimary Whether this is the default serving for the food.
 */


internal data class ServingOption (

    /* Opaque serving id; may look numeric but is always a string. */
    @Json(name = "id")
    val id: kotlin.String?,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal?,

    @Json(name = "unit")
    val unit: kotlin.String?,

    /* Multiplier applied to the food's nutrition values for this serving. */
    @Json(name = "scaling_factor")
    val scalingFactor: java.math.BigDecimal?,

    @Json(name = "weight_grams")
    val weightGrams: java.math.BigDecimal?,

    /* Whether this is the default serving for the food. */
    @Json(name = "is_primary")
    val isPrimary: kotlin.Boolean?

) {


}
