/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.DietPreference
import ai.january.partner.transport.models.DietRestriction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param dietRestrictions Allergens/ingredients to avoid. Omit it (or send []) if none apply.
 * @param dietPreferences Dietary patterns to match. Omit it (or send []) if none apply.
 */


internal data class SuggestFoodAlternativesBody (

    /* Allergens/ingredients to avoid. Omit it (or send []) if none apply. */
    @Json(name = "diet_restrictions")
    val dietRestrictions: kotlin.collections.List<DietRestriction>? = null,

    /* Dietary patterns to match. Omit it (or send []) if none apply. */
    @Json(name = "diet_preferences")
    val dietPreferences: kotlin.collections.List<DietPreference>? = null

) {


}
