/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodAlternative

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param alternatives Healthier alternatives matching the restrictions and preferences. An empty array is a valid result, not an error.
 */


internal data class SuggestFoodAlternativesResponse (

    /* Healthier alternatives matching the restrictions and preferences. An empty array is a valid result, not an error. */
    @Json(name = "alternatives")
    val alternatives: kotlin.collections.List<FoodAlternative>

) {


}
