/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.FoodLogInputFood

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param foods
 * @param timestampUtc UTC consumption time, ending in Z.
 * @param name
 */


internal data class UpdateFoodLogBody (

    @Json(name = "foods")
    val foods: kotlin.collections.List<FoodLogInputFood>? = null,

    /* UTC consumption time, ending in Z. */
    @Json(name = "timestamp_utc")
    val timestampUtc: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

) {


}
