/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.january.partner.transport.models

import ai.january.partner.transport.models.WaterAmount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param id Save this id to delete the log.
 * @param amount
 * @param consumedAt When the water was consumed. UTC, with milliseconds.
 */


internal data class WaterLog (

    /* Save this id to delete the log. */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "amount")
    val amount: WaterAmount,

    /* When the water was consumed. UTC, with milliseconds. */
    @Json(name = "consumed_at")
    val consumedAt: java.time.OffsetDateTime

) {


}
